// Generated by CoffeeScript 1.3.3
(function() {
  var fs, runner;

  fs = require('fs');

  runner = function() {
    var config, livereload, opts, path, resolve, server, _ref;
    livereload = require('./livereload');
    resolve = require('path').resolve;
    opts = require('opts');
    opts.parse([
      {
        short: "p",
        long: "port",
        description: "Specify the port",
        value: true,
        required: false
      }, {
        short: "c",
        long: "config",
        description: "specify the JSON config file",
        value: true,
        required: false
      }
    ].reverse(), true);
    config = {};
    if (opts.get('config') != null) {
      config = JSON.parse(fs.readFileSync(opts.get('config')));
    }
    config.port = opts.get('port') || config.port;
    if ((_ref = config.debug) == null) {
      config.debug = true;
    }
    server = livereload.createServer(config);
    path = resolve(process.argv[2] || '.');
    console.log("Starting LiveReload on port " + server.config.port + " for " + path);
    return server.watch(path);
  };

  module.exports = {
    run: runner
  };

}).call(this);
